name = "BARON"
uuid = "2e2ca445-9e14-5b13-8677-4410f177f82b"
repo = "https://github.com/jump-dev/BARON.jl.git"
version = "0.8.6"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
MathOptInterface = "1.17"
julia = "1.6"
